{% set name = "bth5" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Quansight/bitemporal-h5/releases/download/{{ version }}/bitemporal-h5-{{ version }}.tar.gz
  sha256: 4ff9f419b44e29f2d8e9db2a5188604b7609a368c4d4f5c95a7236c250958eee

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - h5py >=2.8
    - numpy >=1.16
    - numba >=0.45

test:
  imports:
    - bth5

about:
  home: https://github.com/Quansight/bitemporal-h5
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A generic bitemporal model built on HDF5 (h5py)'

extra:
  recipe-maintainers:
    - scopatz
