travis:
  secure:
    BINSTAR_TOKEN: eevAcpn/UGjYefF/9yfSBIzeZoBnA2TW3yQi4GssIsxGeag2dG1MoybGmk5maAL4cj0C90lI4+QjRd6w0SL1nq1SqB/js1UQCi11CNZr70aaTM60Mfo9VCZ12BxCgjubLle26VkiwIrFrUtn5i4sezx7E8dlQd6Su4e1+bpCzqUtSJoxStinJquYjueQekmm4EsQPITnEImu6jWrqTqqBN+yj/9Vew1VDaDE5r3VJ089D4pagrIKNTmI4FJQurAaM+UECWiVibi1W0eVJ/lZyL/K4y5E6mr7xTAFfy7/6S38/Z7yzsc504Zexj4jPScDWRZ1iNdCkQcc5vl4PxVP9my9MWG7XkzrnbbYCkMnAKlI1yoKJsmxtsgRAmk5w4fjPJ/RDlFwUmHAvMvm97E1PFeJqUq3DYZz+dprcMODsvTsTcW6JOkBVoPpDveEohyRdc/I4RgeD8u4Qfun7ud9Xzq8sCsXc9ku6X90kCjm8926aXJW7JyJdZKlZ0wfGXc7UIkaW3YPPtP7zyxUgio4JXO1n1RGUWZ9sU9T2Ay2B9avNPkvzPxUHNfBS8nwMdy6cg8zaTZACGB9sIkrW46Flz8TWhlfP9KN5C8Bc9RpFGYkxiKU4twVI3+WB6kMKtsEoNkCXxNO9K2osqvgNaSMMs4a/DUVYHnfpGZM2uTKTDo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
